name       : redkite
version    : 1.2.0
release    : 7
source     :
    - https://github.com/iurie-sw/redkite/archive/v1.2.0.tar.gz : 2b0fb650e5f94649aab874ce06fadea7f7663a4855163c4e4e49fd5db3677c59
license    : GPL-3.0-or-later
component  : desktop.library
summary    : A small GUI toolkit.
description: |
    Redkite is a small free software GUI toolkit. It is developed in C++17 and inspired from other well known GUI toolkits.
builddeps  :
    - pkgconfig(cairo)
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
