name       : redkite
version    : 1.0.1
release    : 5
source     :
    - https://github.com/iurie-sw/redkite/archive/v1.0.1.tar.gz : d868c467334ef28bf50d6b2e8f126e8b0e8d1df158d258faa86942b2426ff25d
license    : GPL-3.0-or-later
component  : desktop.library
summary    : A small GUI toolkit.
description: |
    Redkite is a small free software GUI toolkit. It is developed in C++17 and inspired from other well known GUI toolkits.
builddeps  :
    - pkgconfig(cairo)
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
