name       : redkite
version    : 1.0.3
release    : 6
source     :
    - https://github.com/iurie-sw/redkite/archive/v1.0.3.tar.gz : 460bf0c97babea7003e0dbceccc62f2b77c193a53797bb5834c442b57112d98b
license    : GPL-3.0-or-later
component  : desktop.library
summary    : A small GUI toolkit.
description: |
    Redkite is a small free software GUI toolkit. It is developed in C++17 and inspired from other well known GUI toolkits.
builddeps  :
    - pkgconfig(cairo)
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
